from test_version import mvp, additional_info
import pandas as pd
pd.set_option('display.max_columns', 50)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('Welcome to Solana Portfolio Optimizer')
print("\x1B[3m" + 'This portfolio pptimizer helps to minimize your portfolio risk based on your Solana investment' + "\x1B[0m")
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('How much would you like to invest in Solana as percent of your total investment?')
print("\x1B[3m" + 'Example 0.05' + "\x1B[0m")
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
solana_investment = input()
#solana(solana_investment)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('Which coins would you like to add into your portfolio (minimum 2 additional coins)?')
print('Possible coins: BTC, ETH, BNB, ADA, XRP.')
print("\x1B[3m" + 'Example BTC, ETH, ADA' + "\x1B[0m")
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
coins = input()
# print("\x1B[3m" + 'Please wait, i download data :)' + "\x1B[0m")
# choose_coins(coins)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('What is the preferred minimum investment in each chosen coin as percent of your total investment?')
print('Your coins are %s' % coins)
print("\x1B[3m" + 'If you have no preferences for the minimum investment please write 0.0' + "\x1B[0m")
print("\x1B[3m" + 'Example 0.1, 0.2, 0.0' + "\x1B[0m")
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
limits = input()
print("\x1B[3m" + 'Please wait, i am optimizing your portfolio :)' + "\x1B[0m")
mvp(coins, limits, solana_investment)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('Would you like to get more information about your portfolio?')
print("\x1B[3m" + 'Example ok' + "\x1B[0m")
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
x = input()
additional_info(coins, limits, solana_investment, x)
